import React from "react";

const sizeClasses = {
  txtCairoBold20RedA200aa: "font-bold font-cairo",
  txtOpenSansBold14Lightblue300: "font-bold font-opensans",
  txtOpenSans14Deeppurple600: "font-normal font-opensans",
  txtCairoSemiBold16: "font-cairo font-semibold",
  txtOpenSansRomanSemiBold14RedA200: "font-opensans font-semibold",
  txtOpenSans14Gray50001: "font-normal font-opensans",
  txtOpenSansBold14Green500: "font-bold font-opensans",
  txtCairoSemiBold18: "font-cairo font-semibold",
  txtOpenSans12Bluegray700: "font-normal font-opensans",
  txtCairoSemiBold20RedA200aa: "font-cairo font-semibold",
  txtCairoBold12: "font-bold font-cairo",
  txtOpenSansRomanSemiBold14Lightblue300: "font-opensans font-semibold",
  txtPoppinsSemiBold14: "font-poppins font-semibold",
  txtCairoBold24Green50001: "font-bold font-cairo",
  txtOpenSansBold16Deeppurple600: "font-bold font-opensans",
  txtCairoSemiBold14: "font-cairo font-semibold",
  txtOpenSansBold14WhiteA700: "font-bold font-opensans",
  txtCairoSemiBold16Bluegray700: "font-cairo font-semibold",
  txtPoppinsRegular14WhiteA700: "font-normal font-poppins",
  txtCairoBold18Deeppurple600: "font-bold font-cairo",
  txtCairoSemiBold28: "font-cairo font-semibold",
  txtOpenSans18Gray90001: "font-normal font-opensans",
  txtPoppinsRegular14: "font-normal font-poppins",
  txtOpenSansRomanRegular12: "font-normal font-opensans",
  txtCairoSemiBold20: "font-cairo font-semibold",
  txtCairoBold18Bluegray700: "font-bold font-cairo",
  txtCairoSemiBold18Deeppurple600: "font-cairo font-semibold",
  txtCairoBold14Gray900: "font-bold font-cairo",
  txtCairoSemiBold14WhiteA700: "font-cairo font-semibold",
  txtCairoBold20Gray90001: "font-bold font-cairo",
  txtOpenSansRomanSemiBold14WhiteA700: "font-opensans font-semibold",
  txtCairoSemiBold18Gray90007: "font-cairo font-semibold",
  txtCairoSemiBold20WhiteA700aa: "font-cairo font-semibold",
  txtCairoRegular18WhiteA700: "font-cairo font-normal",
  txtCairoBold20Bluegray700: "font-bold font-cairo",
  txtCairoRegular18RedA200: "font-cairo font-normal",
  txtOpenSansRomanSemiBold14Green500: "font-opensans font-semibold",
  txtOpenSansRomanSemiBold20: "font-opensans font-semibold",
  txtCairoBold24Green500: "font-bold font-cairo",
  txtCairoBold32: "font-bold font-cairo",
  txtOpenSans16Gray40002: "font-normal font-opensans",
  txtCairoBold34: "font-bold font-cairo",
  txtPoppinsRegular10: "font-normal font-poppins",
  txtCairoBold26: "font-bold font-cairo",
  txtPoppinsRegular12: "font-normal font-poppins",
  txtCairoBold28: "font-bold font-cairo",
  txtOpenSansRomanLight14: "font-light font-opensans",
  txtCairoSemiBold16Gray500: "font-cairo font-semibold",
  txtOpenSans24: "font-normal font-opensans",
  txtPoppinsMedium20WhiteA700aa: "font-medium font-poppins",
  txtOpenSansRomanSemiBold18: "font-opensans font-semibold",
  txtPoppinsMedium14RedA200: "font-medium font-poppins",
  txtOpenSansRomanSemiBold16: "font-opensans font-semibold",
  txtCairoBold24BlueA400: "font-bold font-cairo",
  txtCairoBold20: "font-bold font-cairo",
  txtOpenSansRomanSemiBold14: "font-opensans font-semibold",
  txtCairoBold24: "font-bold font-cairo",
  txtCairoSemiBold18Gray40001: "font-cairo font-semibold",
  txtCairoBold14: "font-bold font-cairo",
  txtCairoBold16: "font-bold font-cairo",
  txtCairoBold18: "font-bold font-cairo",
  txtCairoBold34Gray90001: "font-bold font-cairo",
  txtCairoBold20WhiteA700aa: "font-bold font-cairo",
  txtOpenSans12Gray50001: "font-normal font-opensans",
  txtCairoSemiBold20Bluegray900: "font-cairo font-semibold",
  txtOpenSansRomanSemiBold14Pink400: "font-opensans font-semibold",
  txtCairoBold20Deeppurple600: "font-bold font-cairo",
  txtPoppinsMedium20Gray90001: "font-medium font-poppins",
  txtCairoBold24Gray50001: "font-bold font-cairo",
  txtCairoBold28Pink400: "font-bold font-cairo",
  txtCairoBold28Deeppurple600: "font-bold font-cairo",
  txtPoppinsMedium20RedA200aa: "font-medium font-poppins",
  txtOpenSansBold16Green500: "font-bold font-opensans",
  txtOpenSansBold14Deeppurple600: "font-bold font-opensans",
  txtOpenSans14: "font-normal font-opensans",
  txtOpenSans16: "font-normal font-opensans",
  txtCairoBold16Deeppurple600: "font-bold font-cairo",
  txtOpenSans18: "font-normal font-opensans",
  txtPoppinsMedium20Bluegray900: "font-medium font-poppins",
  txtCairoSemiBold16Gray50001: "font-cairo font-semibold",
  txtCairoSemiBold16RedA200: "font-cairo font-semibold",
  txtPoppinsMedium16Gray90001: "font-medium font-poppins",
  txtOpenSansBold16WhiteA700: "font-bold font-opensans",
  txtOpenSansBold16Gray50001: "font-bold font-opensans",
  txtCairoSemiBold18RedA200: "font-cairo font-semibold",
  txtCairoBold36: "font-bold font-cairo",
  txtCairoBold14Gray90001: "font-bold font-cairo",
  txtCairoBold38: "font-bold font-cairo",
  txtCairoRegular14WhiteA700: "font-cairo font-normal",
  txtPoppinsMedium20: "font-medium font-poppins",
  txtOpenSansBoldItalic20: "font-bold font-opensans italic",
  txtPoppinsMedium20RedA200: "font-medium font-poppins",
  txtCairoBold20Bluegray900: "font-bold font-cairo",
  txtCairoSemiBold14Bluegray700: "font-cairo font-semibold",
  txtOpenSans12: "font-normal font-opensans",
  txtCairoSemiBold20WhiteA700: "font-cairo font-semibold",
  txtOpenSansBold14Gray50001: "font-bold font-opensans",
  txtCairoSemiBold18WhiteA700: "font-cairo font-semibold",
  txtOpenSans14Pink400: "font-normal font-opensans",
  txtOpenSans16Bluegray700: "font-normal font-opensans",
  txtOpenSansRomanSemiBold16Deeppurple600: "font-opensans font-semibold",
  txtCairoRegular18: "font-cairo font-normal",
  txtOpenSansBold16Orange400: "font-bold font-opensans",
  txtCairoRegular14: "font-cairo font-normal",
  txtOpenSansBold20: "font-bold font-opensans",
  txtOpenSans18Gray50001: "font-normal font-opensans",
  txtOpenSansRomanSemiBold14Deeppurple600: "font-opensans font-semibold",
  txtPoppinsMedium14: "font-medium font-poppins",
  txtCairoBold16Gray50001: "font-bold font-cairo",
  txtCairoBold18Green500: "font-bold font-cairo",
  txtOpenSansSemiBold12: "font-opensans font-semibold",
  txtOpenSans14WhiteA700: "font-normal font-opensans",
  txtCairoSemiBold34: "font-cairo font-semibold",
  txtCairoBold18Gray90001: "font-bold font-cairo",
  txtCairoBold16Bluegray700: "font-bold font-cairo",
  txtOpenSans16Gray50001: "font-normal font-opensans",
  txtOpenSansRomanSemiBold14Gray50001: "font-opensans font-semibold",
  txtPoppinsMedium18: "font-medium font-poppins",
  txtPoppinsMedium16: "font-medium font-poppins",
  txtCairoBold20RedA200: "font-bold font-cairo",
  txtCairoSemiBold20RedA200: "font-cairo font-semibold",
  txtOpenSansBold16: "font-bold font-opensans",
  txtOpenSansBold14: "font-bold font-opensans",
  txtOpenSans12Gray40002: "font-normal font-opensans",
  txtOpenSansRomanSemiBold16Bluegray700: "font-opensans font-semibold",
  txtCairoBold20Gray50001: "font-bold font-cairo",
  txtOpenSans18Bluegray700: "font-normal font-opensans",
  txtCairoSemiBold20Bluegray700: "font-cairo font-semibold",
  txtPoppinsRegular14Gray50001: "font-normal font-poppins",
  txtCairoSemiBold18Gray50001: "font-cairo font-semibold",
};

const Text = ({ children, className = "", size, as, ...restProps }) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
